[General]
network = aodvNetwork
#abstract-config = true (requires omnet 7)

*.numHosts = 10

num-rngs = 3
**.mobility.rng-0 = 1
**.wlan[*].mac.rng-0 = 2

**.constraintAreaMinX = 300m
**.constraintAreaMinY = 300m
**.constraintAreaMinZ = 0m
**.constraintAreaMaxX = 1200m
**.constraintAreaMaxY = 1000m
**.constraintAreaMaxZ = 0m

# mobility
**.host*.mobility.typename = "MassMobility"
**.host*.mobility.initFromDisplayString = false
**.host*.mobility.changeInterval = truncnormal(2s, 0.5s)
**.host*.mobility.angleDelta = normal(0deg, 30deg)
**.host*.mobility.speed = truncnormal(20mps, 8mps)
**.host*.mobility.updateInterval = 100ms

# ping app (host[0] pinged by others)
*.host[0].numApps = 0
*.host[*].numApps = 2
*.host[*].app[*].typename = "PingApp"
*.host[*].app[*].destAddr = "host[0]"
*.host[*].app[0].startTime = uniform(1s,5s)
*.host[*].app[1].startTime = 5s+uniform(1s,5s)
*.host[*].app[*].printPing = true

**.gcs.numUdpApps = 0
**.gcs.udpApp[*].typename = "UDPVideoStreamCli"
**.gcs.udpApp[*].serverAddress = "uav[0](ipv4)"
**.gcs.udpApp[*].localPort = 9999
**.gcs.udpApp[*].serverPort = 3088
**.gcs.udpApp[*].startTime = 0

**.routingFile = ""
**.ip.procDelay = 10us

# ARP configuration
**.arp.retryTimeout = 1s
**.arp.retryCount = 3
**.arp.cacheTimeout = 100s

# nic settings
**.wlan[*].bitrate = 2Mbps

**.wlan[*].mac.dcf.channelAccess.cwMin = 7

**.wlan[*].radio.transmitter.power = 2mW



[Config _IPv4]
#abstract-config = true (requires omnet 7)
description = base for ipv4
*.host[0].app[0].destAddr = "host[1](ipv4)"

[Config IPv4]
description = IPv4 network protocol only (default)
extends=_IPv4
*.host[0].app[0].destAddr = "host[1](ipv4)"

[Config Animations]
description = Setting up some animations
extends = IPv4

*.host[0].wlan[0].radio.displayCommunicationRange = true
*.visualizer.mediumVisualizer.displaySignals = true
*.visualizer.physicalLinkVisualizer.displayLinks = true
*.visualizer.physicalLinkVisualizer.packetFilter = "UDPData*"

[Config _Multi]
#abstract-config = true (requires omnet 7)
description = multiple network protocols
sim-time-limit = 600s
**.host[*].hasIpv4 = true
**.host[*].hasIpv6 = true
**.host[*].hasGn = true
**.host[*].generic.typename = "NextHopNetworkLayer"

[Config MultiIPv4]
description = using Ipv4 on multiple network protocols
extends = _IPv4,_Multi

[Config _Dynamic]
#abstract-config = true (requires omnet 7)
description = some nodes are shut down and restarted trigger route changes
*.host[*].hasStatus = true
*.host[0].status.initialStatus = "down"
*.scenarioManager.script = xmldoc("scenario.xml")

[Config DynamicIPv4]
extends = _Dynamic,_IPv4

[Config Obstacles]
description = Adding obstacles to the environment
extends = _IPv4
network = aodvNetwork

*.physicalEnvironment.config = xmldoc("obstacles.xml")
*.radioMedium.obstacleLoss.typename = "IdealObstacleLoss"